namespace WindowAudioCaptureNative {

runtimeclass AudioFormat {
    AudioFormat(Int32 SampleRate, Int32 BitsPerSample, Int32 Channels);
    Int32 SampleRate {
        get;
    };
    Int32 BitsPerSample {
        get;
    };
    Int32 Channels {
        get;
    };
}

delegate void AudioDataReceivedHandler(UInt8[] data, AudioFormat format);

runtimeclass WindowAudioCapture : Windows.Foundation.IClosable {
    WindowAudioCapture();
    void StartCapture(UInt32 processId);
    void StopCapture();
    AudioFormat CaptureFormat {
        get;
    };
    event AudioDataReceivedHandler AudioDataReceived;
}

}  // namespace WindowAudioCaptureNative